package com.lhd.sys.dao;

import com.lhd.sys.entity.ClassificationofGoodsItem;
import com.lhd.sys.entity.ClassificationofGoodsItemExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
public interface ClassificationofGoodsItemMapper {
	
	List<ClassificationofGoodsItem> goodsItemsById (Integer id) ;
	
	List<ClassificationofGoodsItem> findShopInfoById (Integer id) ;
	
	List<ClassificationofGoodsItem>	searchByBrandsOrPrice (@Param("brand") String brand , @Param("priceOne") Integer priceOne 
							,  @Param("priceTow") Integer priceTow) ;
	
	//熱賣
	List<ClassificationofGoodsItem> hotBuy (@Param("brand") String brand , @Param("priceOne") Integer priceOne 
										,  @Param("priceTow") Integer priceTow) ;
	
	//根据收藏商品推荐   如果用户登录
	List<ClassificationofGoodsItem> findByUserid ( @Param("brand") String brand , @Param("priceOne") Integer priceOne,
									@Param("priceTow") Integer priceTow, @Param("userId") Integer userId ) ;
	
	
	
	//查找所有
	List<ClassificationofGoodsItem> selectAll ( @Param("brand") String brand , @Param("priceOne") Integer priceOne,
			@Param("priceTow") Integer priceTow) ;
	
	
	
	List<ClassificationofGoodsItem> findShopByDesc ( @Param("brand") String brand , @Param("priceOne") Integer priceOne,
			@Param("priceTow") Integer priceTow) ;
	
	
	//默认推荐
	
	/**
	 * 模糊查询
	 */
	List<ClassificationofGoodsItem> fuzzyQuery ( String name ) ;
	
	List<ClassificationofGoodsItem> allGoodsMessage (@Param("cname") String cname
													,@Param("showstatus") Integer showstatus
													,@Param("brand") String brand
													,@Param("priceOne") Double priceOne
													,@Param("priceTow") Double priceTow) ;
	
	
	Integer findMaxId () ;
	
	
	//物理删除
	int updateById ( @Param("showstatus") Integer showstatus , @Param("id") Integer id) ;
	
	
	//修改
	int updateShopById (
						 @Param("cname") String cname
						 ,@Param("inventory") Double inventory
						 ,@Param("price") Double price
						 ,@Param("brand") String brand
						 ,@Param("createtime") Date createtime
						 ,@Param("detail") String detail 
						 , @Param("id") Integer id
						 ,@Param("cid") Integer cid ) ;
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    long countByExample(ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int deleteByExample(ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int insert(ClassificationofGoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int insertSelective(ClassificationofGoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    List<ClassificationofGoodsItem> selectByExample(ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    ClassificationofGoodsItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ClassificationofGoodsItem record, @Param("example") ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int updateByExample(@Param("record") ClassificationofGoodsItem record, @Param("example") ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int updateByPrimaryKeySelective(ClassificationofGoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int updateByPrimaryKey(ClassificationofGoodsItem record);
}