package com.lhd.sys.dao;

import com.lhd.sys.entity.MiaoSha;
import com.lhd.sys.entity.MiaoShaExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MiaoShaMapper {
	
	List<MiaoSha> allMiaoShaMessage ( @Param("cname") String cname
									 ,@Param("cofname") String cofname
									 ,@Param("priceOne") Double priceOne
									 ,@Param("priceTow") Double priceTow) ;
	
	
	Integer findMaxId () ;
	
	
	void updateMiaoShaShopById ( @Param("cname") String cname
							   , @Param("num") Integer num
							   , @Param("price") Double price
							   , @Param("cOfName") String cOfName
							   , @Param("createTime") Date createTime
							   , @Param("cOfId") Integer cOfId
							   , @Param("content") String content
							   , @Param("id") Integer id) ;
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    long countByExample(MiaoShaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int deleteByExample(MiaoShaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int insert(MiaoSha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int insertSelective(MiaoSha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    List<MiaoSha> selectByExample(MiaoShaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    MiaoSha selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") MiaoSha record, @Param("example") MiaoShaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int updateByExample(@Param("record") MiaoSha record, @Param("example") MiaoShaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int updateByPrimaryKeySelective(MiaoSha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miao_sha
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int updateByPrimaryKey(MiaoSha record);
}