package com.lhd.sys.dao;

import com.lhd.sys.entity.MiaoshaOrderImg;
import com.lhd.sys.entity.MiaoshaOrderImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MiaoshaOrderImgMapper {
	
	void addImgCid ( @Param("cid") Integer cid) ;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    long countByExample(MiaoshaOrderImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int deleteByExample(MiaoshaOrderImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int insert(MiaoshaOrderImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int insertSelective(MiaoshaOrderImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    List<MiaoshaOrderImg> selectByExample(MiaoshaOrderImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    MiaoshaOrderImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") MiaoshaOrderImg record, @Param("example") MiaoshaOrderImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int updateByExample(@Param("record") MiaoshaOrderImg record, @Param("example") MiaoshaOrderImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int updateByPrimaryKeySelective(MiaoshaOrderImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order_img
     *
     * @mbg.generated Sat Feb 29 10:17:04 CST 2020
     */
    int updateByPrimaryKey(MiaoshaOrderImg record);
}