package com.lhd.sys.dao;

import com.lhd.sys.entity.SysDept;
import com.lhd.sys.entity.SysDeptExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDeptMapper {
	
	List<SysDept> allFindSysDeptinfo (@Param("id") Integer id 
						, @Param("pid") Integer pid 
						,@Param("remark") String remark
						, @Param("address") String address 
						,@Param("title") String title
						,@Param("available") String available) ;
	
	
	Integer maxorderNum () ;
	
	int updateById (@Param("available") String available
					,@Param("createtime") Date createtime
					,@Param("id") Integer id ) ;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    long countByExample(SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    int deleteByExample(SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    int insert(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    int insertSelective(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    List<SysDept> selectByExample(SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    SysDept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysDept record, @Param("example") SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    int updateByExample(@Param("record") SysDept record, @Param("example") SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    int updateByPrimaryKeySelective(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    int updateByPrimaryKey(SysDept record);
}