package com.lhd.sys.dao;

import com.lhd.sys.entity.SysNotice;
import com.lhd.sys.entity.SysNoticeExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysNoticeMapper {
	
	List<SysNotice> allFindSysNotice (@Param("title") String title 
			, @Param("opername") String opername 
			,@Param("startTime") Date startTime , @Param("endTime") Date endTime) ;
	
	
	void batchDelete ( Integer [] ids) ;
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    long countByExample(SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int deleteByExample(SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int insert(SysNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int insertSelective(SysNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    List<SysNotice> selectByExample(SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    SysNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysNotice record, @Param("example") SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByExample(@Param("record") SysNotice record, @Param("example") SysNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByPrimaryKeySelective(SysNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notice
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByPrimaryKey(SysNotice record);
}