package com.lhd.sys.dao;

import com.lhd.sys.entity.SysPermission;
import com.lhd.sys.entity.SysPermissionExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysPermissionMapper {
	
	List<SysPermission> allFindSysMenuinfo (@Param("id") Integer id 
			, @Param("pid") Integer pid 
			,@Param("type") String type
			,@Param("title") String title
			,@Param("available") Integer available) ;


	Integer maxorderNum () ;
	
	int updateById (@Param("available") Integer available
					,@Param("id") Integer id ) ;
	
	
	List<SysPermission> allFindSysPermissioninfo(@Param("id") Integer id 
									, @Param("pid") Integer pid 
									,@Param("name") String name
									,@Param("type") String type
									,@Param("percode") String percode
									,@Param("available") Integer available) ;
	
	List<SysPermission> findByroleId ( List<Integer> ids) ;
	
	
	List<SysPermission> findPidOfPermission (@Param("available") Integer available
											,@Param("type") String type
											,@Param("list") List<Integer> pids) ;
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    long countByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int deleteByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int insert(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int insertSelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    List<SysPermission> selectByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    SysPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysPermission record, @Param("example") SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByExample(@Param("record") SysPermission record, @Param("example") SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByPrimaryKeySelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByPrimaryKey(SysPermission record);
}