package com.lhd.sys.dao;

import com.baomidou.mybatisplus.mapper.BaseMapper;
import com.lhd.sys.entity.UsersTable;
import com.lhd.sys.entity.UsersTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersTableMapper extends BaseMapper<UsersTable> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    long countByExample(UsersTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    int deleteByExample(UsersTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    Integer insert(UsersTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    int insertSelective(UsersTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    List<UsersTable> selectByExample(UsersTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    UsersTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") UsersTable record, @Param("example") UsersTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    int updateByExample(@Param("record") UsersTable record, @Param("example") UsersTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    int updateByPrimaryKeySelective(UsersTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Mon Feb 10 15:08:47 CST 2020
     */
    int updateByPrimaryKey(UsersTable record);
}