package com.lhd.sys.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModelProperty;


public class ClassificationofGoodsItem implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@ApiModelProperty(value="描述",name="detail",required=true)
	 private String detail;
	 
	@ApiModelProperty(value="是否显示",name="showstatus",required=true)
	 private Integer showstatus;
	 
	 //是否为秒杀商品
	 private Integer miaoShop ;
	
	//第一个价格
	 @ApiModelProperty(value="为价格筛选",name="priceOne")
	private Double priceOne ;
	 
	//第二个价格
	 @ApiModelProperty(value="为价格筛选",name="priceTow")
	private Double priceTow ; 
	
	 @ApiModelProperty(value="发布时间",name="createtime")
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	private Date createtime ;
	
	
	private List<Imginfo> imginfos ;
	
	
	
    public Integer getMiaoShop() {
		return miaoShop;
	}

	public void setMiaoShop(Integer miaoShop) {
		this.miaoShop = miaoShop;
	}

	public Integer getShowstatus() {
		return showstatus;
	}

	public void setShowstatus(Integer showstatus) {
		this.showstatus = showstatus;
	}

	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public List<Imginfo> getImginfos() {
		return imginfos;
	}

	public void setImginfos(List<Imginfo> imginfos) {
		this.imginfos = imginfos;
	}

	public Date getCreateTime() {
		return createtime;
	}

	public void setCreateTime(Date createTime) {
		this.createtime = createTime;
	}

	public Double getPriceOne() {
		return priceOne;
	}

	public void setPriceOne(Double priceOne) {
		this.priceOne = priceOne;
	}

	public Double getPriceTow() {
		return priceTow;
	}

	public void setPriceTow(Double priceTow) {
		this.priceTow = priceTow;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.id
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
	@ApiModelProperty(value="商品id",name="id")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.cId
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
	@ApiModelProperty(value="商品分类id",name="cid",required=true)
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.cName
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
	@ApiModelProperty(value="商品名称",name="cname",required=true)
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.inventory
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
	@ApiModelProperty(value="商品库存",name="inventory",required=true)
    private Double inventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.images
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
	@ApiModelProperty(value="商品图片",name="images")
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.price
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
	@ApiModelProperty(value="商品价格",name="price",required=true)
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.id
     *
     * @return the value of classificationof_goods_item.id
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
	@ApiModelProperty(value="orderno",name="orderno")
    private String orderno;
    
	@ApiModelProperty(value="商品品牌",name="brand",required=true)
    private String brand;
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.id
     *
     * @param id the value for classificationof_goods_item.id
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.cId
     *
     * @return the value of classificationof_goods_item.cId
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.cId
     *
     * @param cid the value for classificationof_goods_item.cId
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.cName
     *
     * @return the value of classificationof_goods_item.cName
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.cName
     *
     * @param cname the value for classificationof_goods_item.cName
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.inventory
     *
     * @return the value of classificationof_goods_item.inventory
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public Double getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.inventory
     *
     * @param inventory the value for classificationof_goods_item.inventory
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public void setInventory(Double inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.images
     *
     * @return the value of classificationof_goods_item.images
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.images
     *
     * @param images the value for classificationof_goods_item.images
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.price
     *
     * @return the value of classificationof_goods_item.price
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.price
     *
     * @param price the value for classificationof_goods_item.price
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }
    
	public String getOrderNo() {
		return orderno;
	}

	public void setOrderNo(String orderno) {
		this.orderno = orderno;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Override
	public String toString() {
		return "ClassificationofGoodsItem [detail=" + detail + ", showstatus=" + showstatus + ", miaoShop=" + miaoShop
				+ ", priceOne=" + priceOne + ", priceTow=" + priceTow + ", createTime=" + createtime + ", imginfos="
				+ imginfos + ", id=" + id + ", cid=" + cid + ", cname=" + cname + ", inventory=" + inventory
				+ ", images=" + images + ", price=" + price + ", orderNo=" + orderno + ", brand=" + brand + "]";
	}

}