package com.lhd.sys.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModelProperty;

public class SysDept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.id
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.pid
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    @ApiModelProperty(value="上级部门",name="pid",required=true)
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.title
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    @ApiModelProperty(value="部门名称",name="title",required=true)
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.open
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    @ApiModelProperty(value="是否展开",name="open")
    private Integer open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.remark
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    @ApiModelProperty(value="部门简介",name="remark",required=true)
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.address
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    @ApiModelProperty(value="部门地址",name="address",required=true)
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.available
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    @ApiModelProperty(value="是否可用",name="available")
    private String available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.ordernum
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    @ApiModelProperty(value="排序顺序",name="ordernum",required=true)
    private Integer ordernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.createtime
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    @ApiModelProperty(value="成立时间",name="createtime")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.id
     *
     * @return the value of sys_dept.id
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.id
     *
     * @param id the value for sys_dept.id
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.pid
     *
     * @return the value of sys_dept.pid
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.pid
     *
     * @param pid the value for sys_dept.pid
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.title
     *
     * @return the value of sys_dept.title
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.title
     *
     * @param title the value for sys_dept.title
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.open
     *
     * @return the value of sys_dept.open
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public Integer getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.open
     *
     * @param open the value for sys_dept.open
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public void setOpen(Integer open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.remark
     *
     * @return the value of sys_dept.remark
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.remark
     *
     * @param remark the value for sys_dept.remark
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.address
     *
     * @return the value of sys_dept.address
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.address
     *
     * @param address the value for sys_dept.address
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.available
     *
     * @return the value of sys_dept.available
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.available
     *
     * @param available the value for sys_dept.available
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public void setAvailable(String available) {
        this.available = available == null ? null : available.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.ordernum
     *
     * @return the value of sys_dept.ordernum
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.ordernum
     *
     * @param ordernum the value for sys_dept.ordernum
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.createtime
     *
     * @return the value of sys_dept.createtime
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.createtime
     *
     * @param createtime the value for sys_dept.createtime
     *
     * @mbg.generated Wed Feb 19 09:26:14 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

	@Override
	public String toString() {
		return "SysDept [id=" + id + ", pid=" + pid + ", title=" + title + ", open=" + open + ", remark=" + remark
				+ ", address=" + address + ", available=" + available + ", ordernum=" + ordernum + ", createtime="
				+ createtime + "]";
	}
}