package com.lhd.sys.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class SysLeavebill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.id
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.title
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.content
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.days
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    private Double days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.leavetime
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date leavetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.state
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.userid
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.id
     *
     * @return the value of sys_leavebill.id
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.id
     *
     * @param id the value for sys_leavebill.id
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.title
     *
     * @return the value of sys_leavebill.title
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.title
     *
     * @param title the value for sys_leavebill.title
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.content
     *
     * @return the value of sys_leavebill.content
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.content
     *
     * @param content the value for sys_leavebill.content
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.days
     *
     * @return the value of sys_leavebill.days
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public Double getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.days
     *
     * @param days the value for sys_leavebill.days
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public void setDays(Double days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.leavetime
     *
     * @return the value of sys_leavebill.leavetime
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public Date getLeavetime() {
        return leavetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.leavetime
     *
     * @param leavetime the value for sys_leavebill.leavetime
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public void setLeavetime(Date leavetime) {
        this.leavetime = leavetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.state
     *
     * @return the value of sys_leavebill.state
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.state
     *
     * @param state the value for sys_leavebill.state
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.userid
     *
     * @return the value of sys_leavebill.userid
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.userid
     *
     * @param userid the value for sys_leavebill.userid
     *
     * @mbg.generated Sun Mar 15 10:52:18 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

	@Override
	public String toString() {
		return "SysLeavebill [id=" + id + ", title=" + title + ", content=" + content + ", days=" + days
				+ ", leavetime=" + leavetime + ", state=" + state + ", userid=" + userid + "]";
	}
    
}