package com.lhd.sys.entity;

import io.swagger.annotations.ApiModelProperty;

public class SysPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.id
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.pid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="上级菜单",name="pid",required=true)
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.type
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="菜单类型",name="type",required=true)
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.percode
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="权限名称",name="percode")
    private String percode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.name
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="权限方法",name="name")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.icon
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="菜单图标",name="icon")
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.href
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="跳转地址",name="href")
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.target
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="target",name="target")
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.spread
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="是否展开",name="spread")
    private Integer spread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.ordernum
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="排序号",name="ordernum")
    private Integer ordernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.available
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="是否可用",name="available")
    private Integer available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ permission.title
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    @ApiModelProperty(value="菜单名称",name="title")
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.id
     *
     * @return the value of sys_ permission.id
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.id
     *
     * @param id the value for sys_ permission.id
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.pid
     *
     * @return the value of sys_ permission.pid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.pid
     *
     * @param pid the value for sys_ permission.pid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.type
     *
     * @return the value of sys_ permission.type
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.type
     *
     * @param type the value for sys_ permission.type
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.percode
     *
     * @return the value of sys_ permission.percode
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public String getPercode() {
        return percode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.percode
     *
     * @param percode the value for sys_ permission.percode
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setPercode(String percode) {
        this.percode = percode == null ? null : percode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.name
     *
     * @return the value of sys_ permission.name
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.name
     *
     * @param name the value for sys_ permission.name
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.icon
     *
     * @return the value of sys_ permission.icon
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.icon
     *
     * @param icon the value for sys_ permission.icon
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.href
     *
     * @return the value of sys_ permission.href
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.href
     *
     * @param href the value for sys_ permission.href
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.target
     *
     * @return the value of sys_ permission.target
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.target
     *
     * @param target the value for sys_ permission.target
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.spread
     *
     * @return the value of sys_ permission.spread
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getSpread() {
        return spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.spread
     *
     * @param spread the value for sys_ permission.spread
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setSpread(Integer spread) {
        this.spread = spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.ordernum
     *
     * @return the value of sys_ permission.ordernum
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.ordernum
     *
     * @param ordernum the value for sys_ permission.ordernum
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.available
     *
     * @return the value of sys_ permission.available
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.available
     *
     * @param available the value for sys_ permission.available
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ permission.title
     *
     * @return the value of sys_ permission.title
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ permission.title
     *
     * @param title the value for sys_ permission.title
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

	@Override
	public String toString() {
		return "SysPermission [id=" + id + ", pid=" + pid + ", type=" + type + ", percode=" + percode + ", name=" + name
				+ ", icon=" + icon + ", href=" + href + ", target=" + target + ", spread=" + spread + ", ordernum="
				+ ordernum + ", available=" + available + ", title=" + title + "]";
	}
    
}