package com.lhd.sys.entity;

public class SysRoleUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ role_user.rid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ role_user.uid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ role_user.rid
     *
     * @return the value of sys_ role_user.rid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ role_user.rid
     *
     * @param rid the value for sys_ role_user.rid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ role_user.uid
     *
     * @return the value of sys_ role_user.uid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ role_user.uid
     *
     * @param uid the value for sys_ role_user.uid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}