package com.lhd.sys.entity;

public class SysRolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ role_permission.rid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ role_permission.pid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ role_permission.rid
     *
     * @return the value of sys_ role_permission.rid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ role_permission.rid
     *
     * @param rid the value for sys_ role_permission.rid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ role_permission.pid
     *
     * @return the value of sys_ role_permission.pid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ role_permission.pid
     *
     * @param pid the value for sys_ role_permission.pid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}